name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: todo2phil
        slot-name: 'production'
        package: ./backend

    - name: Deploy Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: todo2phil
        slot-name: 'production'
        package: ./frontend
