name: Build and deploy Node.js app to Azure Web App - todo2phil

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'  # Verwenden Sie die richtige Node.js-Version f端r das Backend
        working-directory: ./backend  # Wechseln Sie zum Backend-Verzeichnis

      - name: npm install, build, and test (Backend)
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./backend  # Stellen Sie sicher, dass die Befehle im Backend-Verzeichnis ausgef端hrt werden

      - name: Zip artifact for backend deployment
        run: zip backend-release.zip ./backend/* -r

      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'  # Verwenden Sie die richtige Node.js-Version f端r das Frontend
        working-directory: ./frontend  # Wechseln Sie zum Frontend-Verzeichnis

      - name: npm install, build, and test (Frontend)
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./frontend  # Stellen Sie sicher, dass die Befehle im Frontend-Verzeichnis ausgef端hrt werden

      - name: Zip artifact for frontend deployment
        run: zip frontend-release.zip ./frontend/* -r

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend-app
          path: backend-release.zip

      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: frontend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend-app

      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend-app

      - name: Unzip backend artifact for deployment
        run: unzip backend-release.zip -d backend

      - name: Unzip frontend artifact for deployment
        run: unzip frontend-release.zip -d frontend

      - name: 'Deploy backend to Azure Web App'
        id: deploy-backend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo2phil-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B75F988788B8494CB7048A31855C4F69 }}
          package: ./backend  # Verweisen Sie auf das Backend-Verzeichnis

      - name: 'Deploy frontend to Azure Web App'
        id: deploy-frontend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo2phil-frontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B75F988788B8494CB7048A31855C4F69 }}
          package: ./frontend  # Verweisen Sie auf das Frontend-Verzeichnis
