name: Build and Deploy to Azure Web App - todo2phil

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present
          cd ../frontend
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifacts for deployment
        run: |
          zip backend-release.zip ./backend/* -r
          zip frontend-release.zip ./frontend/* -r

      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ./*.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts

      - name: Unzip artifacts for deployment
        run: unzip '*.zip'

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo2phil'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B75F988788B8494CB7048A31855C4F69 }}
          package: ./backend

      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo2phil'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B75F988788B8494CB7048A31855C4F69 }}
          package: ./frontend
